name: .NET Core (master)

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        dotnet-version: 3.1.101
        source-url: https://nuget.pkg.github.com/annocholik/index.json
    
    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Generate NuGet package
      run: dotnet pack -c Release -o out  

    - name: Push generated package to GitHub registry
      run: dotnet nuget push ./out/*.nupkg --skip-duplicate --no-symbols true
      
    
